version: '2'
services:
  redis:
    image: redis:3.2.8
    ports:
      - "6379:6379"
    logging:
      driver: "none"
    environment:
      - "constraint:node.role==master"

  db:
    image: mongo:3.4
    ports: 
      - "27017:27017"
    logging:
      driver: "none"
    environment:
      - "constraint:node.role==master"

  importer:
    build: .
    env_file: 
      - ENV
    environment:
      - "constraint:node.role==worker"
    volumes:
      - .:/app
    links:
      - db
      - redis
    working_dir: /app
    command: python -u import.py

  scheduler:
    build: .
    env_file: 
      - ENV
    environment:
      - "constraint:node.role==worker"
    volumes:
      - .:/app
    links:
      - db
      - redis
    working_dir: /app
    command: python -u scheduler.py

  fetcher:
    build: .
    env_file: 
      - ENV
    environment:
      - "constraint:node.role==worker"
    volumes:
      - .:/app
    links:
      - db
      - redis
    working_dir: /app
    command: python -u fetcher.py

  parser:
    build: .
    env_file: 
      - ENV
    environment:
      - "constraint:node.role==worker"
    volumes:
      - .:/app
    links:
      - db
      - redis
    working_dir: /app
    command: python -u parser.py

  web:  
    build: .
    ports:
      - "8000:8000"
    env_file: 
      - ENV
    environment:
      - "constraint:node.role==master"
    volumes:
      - .:/app
    links:
      - db
      - redis
    working_dir: /app
    command: python -u web.py