scheduler:
  build: .
  env_file: 
    - ENV
  volumes:
    - .:/app
  links:
    - db
    - redis
  working_dir: /app
  command: python scheduler.py
fetcher:
  build: .
  env_file: 
    - ENV
  volumes:
    - .:/app
  links:
    - db
    - redis
  working_dir: /app
  command: python fetcher.py
redis:
  image: redis:latest
  ports:
    - "6379:6379"
db:
  image: mongo:3.4
  ports: 
    - "27017:27017"
