fetcher:
  build: .
  env_file: 
    - ENV
  ports:
    - "8000:8000"
  volumes:
    - .:/app
  links:
    - db
    - redis
  working_dir: /app
  command: python fetcher.py
redis:
  image: redis:latest
db:
  image: mongo:3.4
  ports: 
    - "27017:27017"
